#!/usr/bin/env bash
# 2019 Jose Luis Blas Ralde a.k.a Odyssey2247
#email: regex1024@gmail.com
#script to launch and manage tide
echo ""
echo "██████╗ ████████╗ ██████╗  ██████╗ ██╗     ██╗███╗   ██╗"
echo "██╔══██╗╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██║████╗  ██║"
echo "██████╔╝   ██║   ██║   ██║██║   ██║██║     ██║██╔██╗ ██║"
echo "██╔══██╗   ██║   ██║   ██║██║   ██║██║     ██║██║╚██╗██║"
echo "██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗██║██║ ╚████║"
echo "╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚═╝╚═╝  ╚═══╝"
echo "Tool for manage BlackArch tools"
echo ""
echo "https://github.com/Odyssey2247/btoolin"
echo "website: https://codegsi.group"
echo ""
if  [ -f /etc/pacman.d/blackarch-mirrorlist ]
           	then
           		
           		echo -n "Total BlackArch tools: "
           		pacman -Sgg | grep blackarch | cut -d' ' -f2 | sort -u | wc -l
           		echo -n "Total installed: "
           		pacman -Ss | grep  blackarch | grep installed | wc -l
fi
function helpt(){
  echo ""
  echo  "usage:"
  echo  "btoolin -r -l -t -i -s -n -h"
  echo  " "
  echo  "-r install BlackArch repo"
  echo  " "
  echo  "-l list BlackArch categories"
  echo  " "
  echo  "-t list BlackArch tools"
  echo  " "
  echo  "-i install tool/category"
  echo  "   btoolin -i nmap"
  echo  " "
  echo  "-s search tool/category/criteria"
  echo  "   btoolin -s social"
  echo  " "
  echo  "-n list installed tools"
  echo  " "
  echo  "-h this help:"
  echo  " "
}

arg="$1"
  case $arg in
      -r)
           if  [ -f /etc/pacman.d/blackarch-mirrorlist ]
           	then
           		echo ""
           		echo "Repo BlackArch already installed"
           		echo ""
           	else
           	    echo ""
           		echo "Install BlackArch erpo"
           		echo -n "Download script installer"
           		curl -s -O https://blackarch.org/strap.sh > /dev/null
           		if [ $? -eq 0 ]; then echo " ....ok"; else " ERROR: check your internet conection"; fi
                echo -n "Check md5sum  installer"
           		sha1sum strap.sh > /dev/null
           		if [ $? -eq 0 ]; then echo " ....ok"; else " ERROR: corrupt download please try again";fi
           		chmod +x strap.sh
           		echo -n "Install respo: "
           		sudo ./strap.sh
           fi
            shift
            ;;
	  -t)
	        echo ""
	        echo -n "List all BlackArch tools: "
	        pacman -Sgg | grep blackarch | cut -d' ' -f2 | sort -u | wc -l
	        echo "----------------------------------"
	        pacman -Sgg | grep blackarch | cut -d' ' -f2 | sort -u | more
	        echo ""
            shift
            ;;
      -l)
		    echo ""
		    echo -n "BlackArch categories: "
		    pacman -Sg | grep blackarch | wc -l
		    echo "----------------------------------"
		    pacman -Sg | grep blackarch
            shift
            ;;
      -i)
            echo ""
            echo -n "Installing $2 "
            sudo pacman -S $2
            shift
            ;;
      -s)
            echo ""
            echo -n "Searching $2 "
            echo "output format: "
            echo "<prog> <version> (category) <description>"
            echo ""
            echo -n "Found: "
            pacman -Ss $2 | grep -A1 blackarch |cut -d '/' -f 2 | wc -l
            echo "----------------------------------"
            pacman -Ss $2 | grep -A1 blackarch |cut -d '/' -f 2 | awk '{if (NR > 1 && NR % 2 == 1) print "3[0;32m"$1"3[0m"; print "   "; print $0}' | more
            shift
            ;; 
      -n)   echo ""
            echo -n "Installed BlackArch tools: "
            pacman -Ss | grep blackarch | grep installed | cut -d'/' -f2 | cut -d ' ' -f 1 | wc -l
            echo "----------------------------------"
            pacman -Ss | grep blackarch | grep  installed | cut -d'/' -f2
            shift
            ;;                
      -h)
            helpt
            shift
            shift
            ;;
      -*)
            echo ""
            echo "Unrecognized option: $1"
            echo ""
            helpt
            shift
            shift
            ;;
       *)
	       helpt 	
           ;;
    esac 
